services:
  - type: web
    name: pathway
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pathway
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: AWS_REGION
        value: "us-east-2"
      - key: AWS_BUCKET
        value: "ap-pathway-24" 
      - key: AWS_ACCESS_KEY_ID
        value: ""
      - key: AWS_SECRET_ACESS_KEY
        value: ""
      - key: RAILS_ENV
        value: production
     
databases:
- name: pathway
  plan: free
  databaseName: pathway
  user: pathway
  ipAllowList: []
